apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ycbwixgrt-dotnet-basic
  janus-idp.io/tekton: ycbwixgrt-dotnet-basic
  backstage.io/kubernetes-id: ycbwixgrt-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ycbwixgrt-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
